@baseURL = http://localhost:8080/api/product

### Hibernate
POST {{baseURL}}/hibernate?total=30000

### JDBC
POST {{baseURL}}/jdbc?total=30000

### JDBC with Multi Threading
POST {{baseURL}}/jdbc-threading?total=30000